=begin
Answer.create(:id => 25, :value => "gasdgasg", :question_id => 1, :application_id => 16)
Answer.create(:id => 26, :value => "asdgsag", :question_id => 2, :application_id => 16)
Answer.create(:id => 27, :value => "sdfsadf2222sadf", :question_id => 3, :application_id => 16)
Answer.create(:id => 28, :value => "sdfasdfas333FSA", :question_id => 4, :application_id => 16)
Answer.create(:id => 29, :value => "sadfsadfa4444SFD", :question_id => 5, :application_id => 16)
Answer.create(:id => 31, :value => "sdfsadf65445643666", :question_id => 7, :application_id => 16)
Answer.create(:id => 32, :question_id => 6, :application_id => 16)
Answer.create(:id => 33, :question_id => 8, :application_id => 16)
Answer.create(:id => 34, :question_id => 9, :application_id => 16)
Answer.create(:id => 35, :question_id => 10, :application_id => 16)
Answer.create(:id => 36, :question_id => 11, :application_id => 16)
Answer.create(:id => 37, :question_id => 12, :application_id => 16)
Answer.create(:id => 38, :question_id => 14, :application_id => 16)
Answer.create(:id => 39, :value => "ewtwertwer", :question_id => 15, :application_id => 16)
Answer.create(:id => 40, :question_id => 16, :application_id => 16)
Answer.create(:id => 41, :question_id => 17, :application_id => 16)
Answer.create(:id => 42, :value => "5", :question_id => 0, :application_id => 16)
Answer.create(:id => 43, :value => "8", :question_id => 18, :application_id => 16)
=end