Market.create(:id => 1, :description => "Automotriz")
Market.create(:id => 2, :description => "Comunicaciones y Conectividad")
Market.create(:id => 3, :description => "Desarrollo de Software")
Market.create(:id => 4, :description => "Distribución y Venta al por menor")
Market.create(:id => 5, :description => "Domótica y Hogar Digital")
Market.create(:id => 6, :description => "Educación")
Market.create(:id => 7, :description => "Energía y Ahorro de Energía")
Market.create(:id => 8, :description => "Entretenimiento: Cultura y Ocio")
Market.create(:id => 9, :description => "Entretenimiento: Eventos")
Market.create(:id => 10, :description => "Entretenimiento: Juegos y Juguetes")
Market.create(:id => 11, :description => "Entretenimiento: Música")
Market.create(:id => 12, :description => "Entretenimiento: Video y Audiovisual")
Market.create(:id => 13, :description => "Entretenimiento: HW,Redes y Plataformas")
Market.create(:id => 14, :description => "Innovación Social")
Market.create(:id => 15, :description => "Internet: Citas Online")
Market.create(:id => 16, :description => "Internet:Servcios Digitales")
Market.create(:id => 17, :description => "Medios de Comunicación y Contenidos")
Market.create(:id => 18, :description => "Moda")
Market.create(:id => 19, :description => "Publicidad")
Market.create(:id => 20, :description => "RRHH: Empleo y Contratación")
Market.create(:id => 21, :description => "Salud y Bienestar")
Market.create(:id => 22, :description => "Sector Agricola")
Market.create(:id => 23, :description => "Seguridad")
Market.create(:id => 24, :description => "Servicios Financieros")
Market.create(:id => 25, :description => "Servicios de Tecnologías de Información ( TI para empresas)")
Market.create(:id => 26, :description => "Servicios sectoriales para las empresas")
Market.create(:id => 27, :description => "Tecnologías Limpias")
Market.create(:id => 28, :description => "Viajes, Turismo, Hotelería")
Market.create(:id => 29, :description => "Alimentos")
