Section.create(:id => 1, :description => "Registro Involucrados")
Section.create(:id => 2, :description => "Conociendo Mejor")
Section.create(:id => 3, :description => "Primero lo primero")
Section.create(:id => 4, :description => "Área Impacto")
Section.create(:id => 5, :description => "Manos a la Obra")
Section.create(:id => 6, :description => "Riesgos")
Section.create(:id => 7, :description => "Comentarios Finales")
Section.create(:id => 8, :description => "Redacción Proyecto")
Section.create(:id => 9, :description => "Conexiones")
