ServiceType.create(:id => 1, :description => "Aplicaciones Moviles")
ServiceType.create(:id => 2, :description => "Crowdsourcing")
ServiceType.create(:id => 3, :description => "Gestión de Relación con clientes(CRM)")
ServiceType.create(:id => 4, :description => "Herramientas de Colaboración")
ServiceType.create(:id => 5, :description => "Instrumentos de Pago")
ServiceType.create(:id => 6, :description => "Infraestructura")
ServiceType.create(:id => 7, :description => "Mercado y Comercio Electronico")
ServiceType.create(:id => 8, :description => "Motores de Busqueda o Herramientas de Directorio")
ServiceType.create(:id => 9, :description => "Optimización y Racionalización de Procesos")
ServiceType.create(:id => 10, :description => "Recomendaciones y Categorizaciones")
ServiceType.create(:id => 11, :description => "Redes Sociales y Comunidades")
ServiceType.create(:id => 12, :description => "Servicios y Aplicaciones en el punto de venta")
ServiceType.create(:id => 13, :description => "Consultoría")
ServiceType.create(:id => 14, :description => "Consultoría Digital")
